# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-03 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190330_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, default=None, help_text='Please supply an icon for this group', max_length=255, null=True),
        ),
    ]
