# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190426_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='perception',
            name='geojson',
            field=models.TextField(default=None, help_text='Please supply a geojson for this Perception'),
            preserve_default=False,
        ),
    ]
