# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_perception_geojson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lider',
            options={'verbose_name_plural': 'Lideres'},
        ),
        migrations.AlterField(
            model_name='perception',
            name='geojson',
            field=models.TextField(blank=True, help_text='Please supply a geojson for this Perception', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lider',
            unique_together=set([]),
        ),
    ]
