# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190427_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Level Group', max_digits=5, null=True),
        ),
    ]
