# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 02:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('app', '0010_group_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Espatial_Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please supply a name for this Category', max_length=255)),
                ('description', models.TextField(help_text='Please supply a description for this Category')),
            ],
        ),
        migrations.CreateModel(
            name='Espatial_Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please supply a name for this group', max_length=255)),
                ('description', models.TextField(help_text='Please supply a description for this group')),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('lat', models.CharField(default=None, help_text='Please supply a latitude for this espatial object', max_length=255)),
                ('lon', models.CharField(default=None, help_text='Please supply a longitude for this espatial object', max_length=255)),
                ('icon', models.CharField(blank=True, default=None, help_text='Please supply an icon for this espatial object', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cat_espatial_object', models.ForeignKey(help_text='Please supply a category for this espatial object', on_delete=django.db.models.deletion.CASCADE, to='app.Category_Espatial_Object')),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, help_text='Please supply an image for this espatial object', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
