# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_espatial_object_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Spatial_Object_Indv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please supply a individual category for each spatial object in the map', max_length=255)),
                ('description', models.TextField(help_text='Please supply a description for this individual category')),
            ],
        ),
        migrations.AlterField(
            model_name='category_espatial_object',
            name='description',
            field=models.TextField(help_text='Please supply a description for this category'),
        ),
        migrations.AlterField(
            model_name='category_espatial_object',
            name='name',
            field=models.CharField(help_text='Please supply a category name for all the spatial objects in the Map', max_length=255),
        ),
        migrations.AlterField(
            model_name='espatial_object',
            name='cat_espatial_object',
            field=models.ForeignKey(help_text='Please supply a general ategory for this espatial object', on_delete=django.db.models.deletion.CASCADE, to='app.Category_Espatial_Object'),
        ),
        migrations.AddField(
            model_name='espatial_object',
            name='cat_spatial_object_indv',
            field=models.ForeignKey(help_text='Please supply a individual category for this espatial object', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category_Spatial_Object_Indv'),
        ),
    ]
