# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_category_spatial_object_indv_color_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_espatial_object',
            options={'verbose_name': 'Mapa', 'verbose_name_plural': 'Mapas'},
        ),
        migrations.AlterModelOptions(
            name='category_spatial_object_indv',
            options={'verbose_name': 'Categoria_Spatial_Object', 'verbose_name_plural': 'Categorias_Spatial_Objects'},
        ),
        migrations.AlterField(
            model_name='category_espatial_object',
            name='description',
            field=models.TextField(help_text='Please supply a description for this Map'),
        ),
        migrations.AlterField(
            model_name='category_espatial_object',
            name='name',
            field=models.CharField(help_text='Please supply a name for this Map', max_length=255),
        ),
    ]
