# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191116_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_espatial_object',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
        migrations.AlterModelOptions(
            name='category_spatial_object_indv',
            options={'verbose_name': 'Category Spatial Object', 'verbose_name_plural': 'Category Spatial Objects'},
        ),
        migrations.AlterModelOptions(
            name='espatial_object',
            options={'verbose_name': 'Spatial Object', 'verbose_name_plural': 'Spatial Objects'},
        ),
        migrations.RemoveField(
            model_name='espatial_object',
            name='cat_espatial_object',
        ),
        migrations.AddField(
            model_name='espatial_object',
            name='Map',
            field=models.ForeignKey(help_text='Please supply a Map for this espatial object', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category_Espatial_Object'),
        ),
    ]
